### ISSUE TITLE
Send event after form dismissing crashes then app (iOS)

### ISSUE THREAD

**Issue by mink-ang** [usabilla/usabilla-u4a-react-native#87] opened 2019-12-08 22:45 UTC
How to reproduce: 
1. Send event (to trigger active form to open)
2. Dismiss the form
3. Reset campaign data
4. Send event again
 Then app crashes.

I tried this with the sample app. 

Note: This only happens when (active) form was dismissed.

**Comment by torkvell** [comment] 2019-12-09 16:50
Hi @mink-ang ,

I've now done some tests on this and I'm not able to reproduce the reported behavior in our test app:

![2019-12-09 at 17 48](https://user-images.githubusercontent.com/40064170/70455269-46a2e880-1aac-11ea-9972-11a0063ad2b5.gif)

What I could do is to do some final testing with your specific appID and campaign event name, please forward this support@usabilla.com so we can assist further on this.

**Comment by mink-ang** [comment] 2019-12-09 21:47
Hi @torkvell , instead of clicking continue, can you click cancel?

**Comment by mink-ang** [comment] 2019-12-09 21:59
![usabilla_crash](https://user-images.githubusercontent.com/41883348/70476666-4dbd0b80-1b2b-11ea-9345-4aadb8c35d7f.gif)

**Comment by torkvell** [comment] 2019-12-10 09:06
Hi @mink-ang ,

Thanks for clarifying. I can confirm this is a bug. A ticket has been created for this and should hopefully be fixed so it's ready for our next release. Our next release will be in approximately 10 days.  

If there is anything else we can assist with, please let me know.

**Comment by keshcreations** [comment] 2020-01-02 12:48
Hi @mink-ang 

Thank you for your patience on this. I'm happy to be able to share that we have fixed this issue in the latest release of our React Native Hybrid SDK. Please upgrade to the latest version of the SDK to implement the fixes on your end as well.

In the new version of our React Native SDK, we also have introduced auto-linking. Based on how our current React Native SDK is installed, this might mean that you will have to install the new SDK differently. In any case, we have included the steps for this in the documentation.

Should you run into any issues, then please feel free to get back in touch.

**Closed** 2020-01-02 12:48 UTC
Labels: bug
