### ISSUE TITLE
crash at setDataMask in swiftBridge module for iOS 

### ISSUE THREAD

**Issue by Venkat1128** [usabilla/usabilla-u4a-react-native#147] opened 2021-09-10 10:51 UTC
We have seen a spike of crashes on our production app with the below stack trace.
We are initializing the SDK and setting up the data mask as follows :

```
usabilla.initialize(config.CAMPAIGN_APP_ID);
usabilla.setDataMasking([Masks.emailMask, Masks.numberMask], Masks.replaceWithChar);
```
We believe that it might be setDataMask is been called before initialization is completed, but can't be sure since we don't have access to the native setDataMask method.

<img width="1296" alt="Screenshot 2021-09-10 at 11 40 23 AM" src="https://user-images.githubusercontent.com/5871460/132841914-b3adc4f6-6325-4b59-8011-98a89f395dd0.png">

**Comment by xanderwernecke** [comment] 2021-09-13 15:08
Hi @Venkat1128 ,

Thank you for reaching out!

Please could you provide me with the following information and I can pass it over to the developers:
**Platform:** 
Android / iOS
SDK version
Device & Device OS version
Steps to reproduce the issue
FormId / AppId / CampaignId
Stack trace / logs

I'm looking forward to your response.

**Comment by Venkat1128** [comment] 2021-09-14 08:10
Thanks for the reply @xanderwernecke 
Please find the details below: 
Platform: iOS 
SDK: v0.13.2
Device & Device OS version: iPhone ( all models) & iOS 14.x 
Steps to reproduce : Issue reported only in production environment 
Stack Trace: 
<img width="1290" alt="Screenshot 2021-09-14 at 9 08 59 AM" src="https://user-images.githubusercontent.com/5871460/133220705-2689bb4f-c07c-4699-b1c2-973bfeda091d.png">

**Comment by xanderwernecke** [comment] 2021-09-14 09:10
Hi @Venkat1128 . 

Thank you for providing me with the additional information. I've passed this onto the Developers and I'll get back to you regarding it once I have an update from them.

Kind Regards,
Xander

**Comment by xanderwernecke** [comment] 2022-01-06 15:14
Hi @Venkat1128 . Thank you for your patience on this case. 

Our Developer's took a look at this, however, were unable to reproduce this issue. Are you still experiencing this crash? 

I'm looking forward to your response!

Kind Regards,
Xander

**Comment by xanderwernecke** [comment] 2022-01-11 14:01
This issue seems to have grown stale and as a result, we will close this ticket for now. Please feel free to open it again if you experience this issue again / continue to experience this issue. 

Kind Regards,

Xander

**Comment by Venkat1128** [comment] 2022-01-14 11:49
Hi, @xanderwernecke  sorry for the late reply. 
We can still see the issue. 
I see an open pr improving setDataMasking will null check. I am not sure if that fix is related to this issue? 
We will wait for that to be released and see how it goes.

Thanks,
Venkat

**Comment by xanderwernecke** [comment] 2022-01-19 11:05
Hi @Venkat1128 , thank you for your response. Set data masking PR isn't related but It has has just been released, please can you let me know if you are still experiencing this issue after this release.

Kind Regards,
Xander

**Comment by Venkat1128** [comment] 2022-02-14 09:08
Hi @xanderwernecke 
We have updated the library to the latest Version in the app, but still the same crash with setDataMasking. The stack trace is also the same.
Any suggestions, please?

Thanks,
Venkat

**Comment by stodorovicc** [comment] 2022-10-18 10:16
Hi @Venkat1128,

Just wanted to follow up on this, is the issue still present? If so, would you be able to provide us a sample or a code snippet?

Thanks in advance,
Slobodan

**Comment by francocm** [comment] 2022-11-10 14:37
Hi @stodorovicc,

I'm replying in @Venkat1128's place. Yes, the issue is still present. We notice:

* it happens when jumping back from a webview into the app using `appscheme://` _(I redacted the actual scheme name)_
* it seems to be a race condition. Works roughly 80% of the time, and to reproduce it simply run the same test repeatedly. We also notice a similar % of crashes in this situation on live traffic.

Below is a stack trace of the crashed thread:

```
Thread 9 Crashed::  Dispatch queue: com.facebook.react.UsabillaBridgeQueue
0   <translation info unavailable>         0x110d434f0 ???
1   <translation info unavailable>         0x1103d109c ???
2   Usabilla                               0x115a7ea28 $sSD8_VariantV20isUniquelyReferencedSbyFSS_8Usabilla20UBTelemetricResponseCTg5 + 8 [inlined]
3   Usabilla                               0x115a7ea28 specialized Dictionary._Variant.removeValue(forKey:) + 72
4   Usabilla                               0x115b1b176 specialized UBTelemetrics.logEnd<A>(for:keyPath:) + 742
5   Usabilla                               0x115ae39fd specialized static UsabillaInternal.setDataMasking(masks:maskCharacter:) + 493 (UsabillaInternal.swift:335)
6   redacted                               0x105727961 UsabillaBridge.setDataMasking(_:_:) + 641 (UsabillaBridge.swift:118)
7   redacted                               0x105727a9a @objc UsabillaBridge.setDataMasking(_:_:) + 250
8   CoreFoundation                         0x117816fdc __invoking___ + 140
9   CoreFoundation                         0x11781434f -[NSInvocation invoke] + 305
10  CoreFoundation                         0x1178145e2 -[NSInvocation invokeWithTarget:] + 70
11  redacted                               0x105416a76 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2534 (RCTModuleMethod.mm:584)
12  redacted                               0x10541a61b facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 731 (RCTNativeModule.mm:114)
13  redacted                               0x10541a181 facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const + 113 (RCTNativeModule.mm:75)
14  redacted                               0x10541a109 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 25 (RCTNativeModule.mm:67)
15  libdispatch.dylib                      0x1176038e4 _dispatch_call_block_and_release + 12
16  libdispatch.dylib                      0x117604b25 _dispatch_client_callout + 8
17  libdispatch.dylib                      0x11760b0df _dispatch_lane_serial_drain + 753
18  libdispatch.dylib                      0x11760bcc1 _dispatch_lane_invoke + 400
19  libdispatch.dylib                      0x11761697b _dispatch_workloop_worker_thread + 779
20  libsystem_pthread.dylib                0x11ab2cfd0 _pthread_wqthread + 326
21  libsystem_pthread.dylib                0x11ab2bf57 start_wqthread + 15
```

_I have replaced the app name with `redacted` above._

**Comment by stodorovicc** [comment] 2023-03-28 10:52
Hi @Venkat1128,

I will close this issue now since it's been a while we got a last response. Feel free to reach back to me if you are still experiencing issues.

Regards,
Slobodan

**Closed by stodorovicc** 2023-03-28 10:52 UTC
Labels: bug, support, pending reply
